const GET_USERS = "GET_USERS"
const GET_USER_INFO = "GET_USER_INFO"
const REQUEST_SUCCESS = "REQUEST_SECCESS"
const REQUEST_FAIL = "REQUEST_FAIL"

export {GET_USERS, GET_USER_INFO, REQUEST_SUCCESS, REQUEST_FAIL}