const GET_USERS = "GET_USERS"
const GET_USER_INFO = "GET_USER_INFO"
const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"
const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS"
const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL"

export {GET_USERS, GET_USER_INFO, LOGIN_REQUEST_SUCCESS, LOGIN_REQUEST_FAIL, REGISTRATION_REQUEST_SUCCESS, REGISTRATION_REQUEST_FAIL}