const GET_USERS = "GET_USERS"
const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS"
const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL"

export {GET_USERS, REGISTRATION_REQUEST_SUCCESS, REGISTRATION_REQUEST_FAIL}