const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"
const LOGIN_REQUEST = "LOGIN_REQUEST"

export {LOGIN_REQUEST, LOGIN_REQUEST_SUCCESS, LOGIN_REQUEST_FAIL}