const GET_USER_INFO = "GET_USER_INFO"
// const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
// const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL"
const USER_INFO_REQUEST = "USER_INFO_REQUEST"
const EDIT_USER_INFO_SUCCESS = "EDIT_USER_INFO_SUCCESS"
const EDIT_USER_INFO_FAIL = "EDIT_USER_INFO_FAIL"


export {GET_USER_INFO, USER_INFO_REQUEST, EDIT_USER_INFO_SUCCESS, EDIT_USER_INFO_FAIL}